spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/application-database
    currentSchema: inventory_service
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        default_schema: inventory_service
    hibernate:
      ddl-auto: validate